/**
 * Natural-language phrases for Places Text Search, aligned with Google Places API (New)
 * Table A primary types (and common synonyms). Not fetched at runtime.
 *
 * @see https://developers.google.com/maps/documentation/places/web-service/place-types
 */

const RAW = [
  "accounting firm",
  "american restaurant",
  "amusement park",
  "appliance store",
  "aquarium",
  "art gallery",
  "asian restaurant",
  "auto parts store",
  "auto repair",
  "auto window tinting service",
  "bakery",
  "banquet hall",
  "bank",
  "bar",
  "barber shop",
  "beauty salon",
  "bicycle shop",
  "bookstore",
  "boat dealer",
  "boat rental service",
  "boat tour agency",
  "bowling alley",
  "brewery",
  "cafe",
  "campground",
  "car accessories store",
  "car alarm supplier",
  "car dealership",
  "car rental",
  "car rental agency",
  "car stereo store",
  "car wash",
  "catering",
  "chauffeur service",
  "chiropractor",
  "church",
  "clothing store",
  "coffee shop",
  "convenience store",
  "courthouse",
  "daycare",
  "deli",
  "dental office",
  "cosmetic dentist",
  "dental clinic",
  "dental hygienist",
  "dental implants",
  "dentist",
  "endodontist",
  "oral surgeon",
  "orthodontist",
  "periodontist",
  "teeth whitening service",
  "department store",
  "dermatologist",
  "doctor",
  "dry cleaner",
  "electrician",
  "cell phone store",
  "ecommerce agency",
  "ecommerce service",
  "electronics company",
  "electronics store",
  "event venue",
  "fast food restaurant",
  "facial spa",
  "fishing store",
  "florist",
  "funeral home",
  "furniture rental service",
  "furniture store",
  "glazier",
  "gas station",
  "gift shop",
  "golf course",
  "grocery store",
  "gym",
  "hair salon",
  "hardware store",
  "health spa",
  "hindu temple",
  "home improvement store",
  "hospital",
  "hotel",
  "ice cream shop",
  "insurance agency",
  "italian restaurant",
  "jewelry store",
  "laundromat",
  "law firm",
  "laser hair removal service",
  "library",
  "limousine service",
  "liquor store",
  "locksmith",
  "lodging",
  "manufacturer",
  "marketing agency",
  "marina",
  "massage spa",
  "meal delivery",
  "meal takeaway",
  "men's clothing store",
  "medical clinic",
  "medical office",
  "medical spa",
  "mexican restaurant",
  "mosque",
  "movie theater",
  "moving company",
  "museum",
  "nail salon",
  "night club",
  "optometrist",
  "painting contractor",
  "park",
  "parking",
  "pet grooming",
  "pet store",
  "permanent make-up clinic",
  "pharmacy",
  "photographer",
  "physiotherapist",
  "pizza restaurant",
  "plumber",
  "pool cleaning service",
  "post office",
  "primary school",
  "architectural designer",
  "bathroom remodeler",
  "commercial real estate agency",
  "construction company",
  "general contractor",
  "home builder",
  "kitchen remodeler",
  "property investment service",
  "property management company",
  "real estate agent",
  "remodeler",
  "real estate agency",
  "restaurant",
  "roofing contractor",
  "rv park",
  "sandwich shop",
  "school",
  "seafood restaurant",
  "secondary school",
  "shoe store",
  "shopping mall",
  "software company",
  "spa",
  "sportswear store",
  "storage facility",
  "supermarket",
  "sushi restaurant",
  "swimming pool contractor",
  "swimming pool repair service",
  "swimming pool supply store",
  "synagogue",
  "t-shirt store",
  "taco restaurant",
  "tanning salon",
  "tattoo shop",
  "tax preparation",
  "tire shop",
  "tourist attraction",
  "towing service",
  "transportation service",
  "travel agency",
  "truck accessories store",
  "university",
  "used car dealer",
  "veterinarian",
  "web designer",
  "wedding venue",
  "wine bar",
  "work clothes store",
  "window installer",
  "window replacement",
  "window service",
  "window service provider",
  "window tinting service",
  "yacht broker",
  "yacht club",
  "yoga studio",
] as const;

function uniqueSorted(strings: readonly string[]): readonly string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const s of strings) {
    const t = s.trim();
    if (!t || seen.has(t)) continue;
    seen.add(t);
    out.push(t);
  }
  out.sort((a, b) => a.localeCompare(b, "en"));
  return out;
}

/** Deduped, alphabetized suggestions for the Prospects Discover category field. */
export const PLACES_TEXT_SEARCH_CATEGORY_SUGGESTIONS: readonly string[] =
  uniqueSorted(RAW);
