/**
 * Natural-language phrases for Places Text Search, aligned with Google Places API (New)
 * Table A primary types (and common synonyms). Not fetched at runtime.
 *
 * @see https://developers.google.com/maps/documentation/places/web-service/place-types
 */

const RAW = [
  "accounting firm",
  "american restaurant",
  "amusement park",
  "aquarium",
  "art gallery",
  "asian restaurant",
  "auto parts store",
  "auto repair",
  "bakery",
  "bank",
  "bar",
  "barber shop",
  "beauty salon",
  "bicycle shop",
  "bookstore",
  "bowling alley",
  "brewery",
  "cafe",
  "campground",
  "car dealership",
  "car rental",
  "car wash",
  "catering",
  "chiropractor",
  "church",
  "clothing store",
  "coffee shop",
  "convenience store",
  "courthouse",
  "daycare",
  "deli",
  "dental office",
  "department store",
  "dermatologist",
  "doctor",
  "dry cleaner",
  "electrician",
  "electronics store",
  "event venue",
  "fast food restaurant",
  "florist",
  "funeral home",
  "furniture store",
  "gas station",
  "gift shop",
  "golf course",
  "grocery store",
  "gym",
  "hair salon",
  "hardware store",
  "hindu temple",
  "home improvement store",
  "hospital",
  "hotel",
  "ice cream shop",
  "insurance agency",
  "italian restaurant",
  "jewelry store",
  "laundromat",
  "law firm",
  "library",
  "liquor store",
  "locksmith",
  "lodging",
  "marina",
  "meal delivery",
  "meal takeaway",
  "medical clinic",
  "mexican restaurant",
  "mosque",
  "movie theater",
  "moving company",
  "museum",
  "nail salon",
  "night club",
  "optometrist",
  "painting contractor",
  "park",
  "parking",
  "pet grooming",
  "pet store",
  "pharmacy",
  "photographer",
  "physiotherapist",
  "pizza restaurant",
  "plumber",
  "post office",
  "primary school",
  "real estate agency",
  "restaurant",
  "roofing contractor",
  "rv park",
  "sandwich shop",
  "school",
  "seafood restaurant",
  "secondary school",
  "shoe store",
  "shopping mall",
  "spa",
  "storage facility",
  "supermarket",
  "sushi restaurant",
  "synagogue",
  "taco restaurant",
  "tanning salon",
  "tattoo shop",
  "tax preparation",
  "tire shop",
  "tourist attraction",
  "towing service",
  "travel agency",
  "university",
  "used car dealer",
  "veterinarian",
  "wine bar",
  "yoga studio",
] as const;

function uniqueSorted(strings: readonly string[]): readonly string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const s of strings) {
    const t = s.trim();
    if (!t || seen.has(t)) continue;
    seen.add(t);
    out.push(t);
  }
  out.sort((a, b) => a.localeCompare(b, "en"));
  return out;
}

/** Deduped, alphabetized suggestions for the Prospects Discover category field. */
export const PLACES_TEXT_SEARCH_CATEGORY_SUGGESTIONS: readonly string[] =
  uniqueSorted(RAW);
